### ISSUE TITLE
all models for different scales

### ISSUE THREAD

**Issue by Jiyongma06** [1adrianb/face-alignment#202] opened 2020-08-19 23:31 UTC
Currently only large models can be downloaded. Are there models for TINY, SMALL, MEDIUM scales.
class NetworkSize(Enum):
    # TINY = 1
    #SMALL = 2
    # MEDIUM = 3
    LARGE = 4

**Comment by 1adrianb** [comment] 2020-12-13 18:54
Duplicate of #4 That being said, I should dig into my old backups and look into this at some point.

**Closed by 1adrianb** 2020-12-13 18:54 UTC
Labels: duplicate
