### ISSUE TITLE
Segmentation Fault Error

### ISSUE THREAD

**Issue by cenaliu** [1adrianb/face-alignment#85] opened 2018-07-10 12:46 UTC
When I execute 'import face_alignment', I meet 'Segmentation fault (core dumped)' and don't know how to debug it. I use Pytorch 0.4.0 and Python 3.6.5 Anaconda.  Would you please help me and tell me what I should do to solve it. Thanks very much.

**Comment by winnie1994** [comment] 2018-07-19 01:22
After I updated pytorch to 0.4, I started getting this behaviour too. 
It seems to be a pytorch0.4+dlib problem-- try running 'import dlib' in commandline python and see if you still get a segfault. Additionally, see https://github.com/pytorch/pytorch/issues/8585
 I'll post an update if I find a fix!

**Comment by 1adrianb** [comment] 2018-07-21 08:17
Hi both,
While it will be slower can you try running dlib in cpu mode to see if you can get around this issue?

Ideally however you should replace dlib with a better face detection method.

**Comment by winnie1994** [comment] 2018-08-08 00:51
Thanks for the response! @cenaliu Compiling dlib from source with a gcc compiler newer than 4.9 solved it. 
(See last post in the issue linked to above.) The prebuilt dlib binaries in pypi are compiled with an older gcc compiler that causes problems with one of pytorch's third party dependencies.

In addition, is there a face detection model you'd particularly recommend? I've been playing around with mtcnn but am looking to try others too.

**Comment by jeongyoonlee** [comment] 2018-08-08 04:02
I can confirm that @winnie1994's solution works for me.

I upgrade `gcc` with `conda` as follows:
```
conda uninstall gcc
conda install -c conda-forge isl=0.17.1
conda install -c bonsai-team gcc-5
```

After that, I compiled and installed `dlib` from the repo, and reinstalled `face-alignment` from the repo.

**Comment by 1adrianb** [comment] 2018-10-03 16:59
@cenaliu @winnie1994 @jeongyoonlee 
It should be all fixed now, in addition SFD face detector is now used by default. Option for using dlib is still preserved. Will update the documentation and add a new model soon.

**Closed by 1adrianb** 2018-10-03 16:59 UTC

**Comment by 1adrianb** [comment] 2018-10-03 19:32
@jeongyoonlee its very good, it should be able to detect the hole range of facial poses
