### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by QuantumLiu** [1adrianb/face-alignment#35] opened 2017-12-08 05:37 UTC
Python 3.5.4 |Anaconda custom (64-bit)| (default, Aug 14 2017, 13:26:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_alignment
>>> from skimage import io
>>> 
>>> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=True, flip_input=False)
Downloading the face detection CNN. Please wait...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quantumliu/pyprojects/face-alignment/face_alignment/api.py", line 84, in __init__
    path_to_detector)
Boost.Python.ArgumentError: Python argument types in
    cnn_face_detection_model_v1.__init__(cnn_face_detection_model_v1, str)
did not match C++ signature:
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

**Comment by 1adrianb** [comment] 2017-12-11 01:58
Duplicate of #34 Please see the answer provided there.

**Closed by 1adrianb** 2017-12-11 01:58 UTC
