### ISSUE TITLE
Smaller pretrained models

### ISSUE THREAD

**Issue by SergeiSamuilov** [1adrianb/face-alignment#124] opened 2019-01-11 13:17 UTC
Adrian, are fewer stacks models available at the moment? Large model is great, but it would be really nice to speed things up a bit.

**Comment by ibrahimsherdil** [comment] 2019-01-17 14:03
Same query. How can we use the NetworkSize.SMALL option? From where can we download the required landmark detector?

**Comment by Ierezell** [comment] 2019-05-21 19:11
Hi, thanks a lot for this beautiful work, it run perfectly fine ! (just slow on cpu but it's normal). 

Same question here, I tried to modify the api with NetworkSize.TINY or to call it with fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D,
                                  flip_input=False, device='cpu', network_size=1)

but when loading the model I got a urllib.error.HTTPError: HTTP Error 404: Not Found 

Traceback here : `Traceback (most recent call last):
  File "getLandmarks3D.py", line 12, in <module>
    flip_input=False, device='cpu', network_size=1)
  File "/home/pedro/.local/lib/python3.7/site-packages/face_alignment/api.py", line 86, in __init__
    network_name, os.path.join(fan_temp_path))
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by Selimonder** [comment] 2020-01-09 12:50
+1 to this. Execution with smaller network size yields 404.

**Comment by danilopeixoto** [comment] 2020-04-01 10:39
Hi Adrian,
Do you have pretrained weights for tiny, small or medium network size hosted online?

The face_alignment package for Python is great!
Thanks.

**Comment by moncio** [comment] 2020-12-12 16:16
I have the same questions than the other colleagues, do we have available pretrained models for smaller networks? I'm pretty interested to use TINY or SMALL to gain some fps. Great job and amazing library @1adrianb !!!

**Comment by 1adrianb** [comment] 2020-12-13 19:01
Duplicate of #4

**Closed by 1adrianb** 2020-12-13 19:01 UTC
Labels: duplicate
