### ISSUE TITLE
Issue with the python code 

### ISSUE THREAD

**Issue by LinusLGL** [1adrianb/face-alignment#282] opened 2021-08-04 15:11 UTC
Hi,

I got the TypeError: __init__() got an unexpected keyword argument 'face_detector_kwargs'

how do i resolve this problem

![image](https://user-images.githubusercontent.com/46456480/128206097-2bf2c166-d4f5-4c0e-9ef8-26d8564cf6f1.png)

**Comment by 1adrianb** [comment] 2021-08-04 15:41
Marked as duplicate of #281 

Please use the same issue that you opened previously to discuss this.

**Closed by 1adrianb** 2021-08-04 15:41 UTC
Labels: duplicate
