### ISSUE TITLE
Does Face Alignment face detection (sfd and blazeface) require connection to internet?

### ISSUE THREAD

**Issue by rakadambi** [1adrianb/face-alignment#234] opened 2020-12-16 09:11 UTC
This is something I found out by accident. 

My internet went down and the code was running. It failed at face detection for both SFD and Blazeface stating that the soket connection failed.

Do we need Intenet connection to run FA?

**Comment by rakadambi** [comment] 2020-12-16 09:24
Pasting the error here. I see this when network goes down.

`raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /hollance/BlazeFace-PyTorch/master/anchors.npy (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fca33019850>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Comment by 1adrianb** [comment] 2020-12-16 10:52
You shouldn't need internet once the models are downloaded. I see however that for blaze face indeed there is one file that is not stored locally. I will push a fix for this.

**Comment by rakadambi** [comment] 2020-12-16 12:01
Hi @1adrianb . It is the same error for SFD as well. At first I thought it was only for blazeface. But it is the same error for SFD

**Comment by 1adrianb** [comment] 2020-12-16 12:13
I've just made a commit that should address the blaze face issue. I am unable to reproduce the error with SFD however.
The model downloading and caching is now in all cases handled by the torch.hub module which is the same used for example by the torchvision pretrained models.

**Comment by rakadambi** [comment] 2020-12-16 12:46
Thank you! Thank you! This is amazing!

**Closed** 2020-12-17 10:30 UTC
